### ISSUE TITLE
Documentation bug: .modernizr-autorc files aren't valid JSON

### ISSUE THREAD

**Issue by tremby** [andersaloof/modernizr-auto-loader#1]
Your example `.modernizr-autorc` files aren't valid JSON, but the module appears to require them to be so.

**Comment by andersaloof** [comment]
Yes, it needs to be valid JSON, I'll update the documentation.

**Comment by tremby** [comment]
In my opinion, additionally giving the file a .json extension would clear up any confusion about what is expected.

Bonus if it could be written in Yaml instead. (Optional dependency?)

**Comment by andersaloof** [comment]
I've clarified the documentation and examples to be valid JSON objects.
