### ISSUE TITLE
Required tests are not re-evaluated when using webpack-dev-server

### ISSUE THREAD

**Issue by tremby** [andersaloof/modernizr-auto-loader#2]
When using webpack-dev-server and a file is edited such that a required test is either added or removed, this isn't noticed, and the bundled tests don't change.

I need to restart webpack-dev-server for things to take effect.

**Comment by andersaloof** [comment]
Hi,

This is actually the correct behaviour (at least for the moment), though it might not be that clear from the documentation.

The loader was built to solve my annoyance with **modernizr-loader**, where I had to specify what tests to run in the configuration. Using customizr solved this for me, but as you have noticed, the loader is run only once, on startup.

A "quick fix" is to comment the import statement, let webpack rebuild and then uncomment for another rebuild. But it might just be quicker to restart building.

But I'm gonna try something later today that might fix it.

**Comment by andersaloof** [comment]
This should be fixed in 0.1.0

**Comment by tremby** [comment]
Seems to work -- great!
